### ISSUE TITLE
CI/CD

### ISSUE THREAD

**Issue by sp94** [sp94/CubicSplines.jl#7]
We should add CI/CD for automatic testing and code coverage

There is the start of a travis.yaml file from #6, but fails on systems without matplotlib installed

- [ ] Remove PyPlot as a dependency?
- [ ] Migrate to GitHub actions? (Travis has placed limits on free usage)

**Comment by StefanMathis** [comment]
I'd vote for migrating to GitHub actions. The Travis file was created by me because it was done the same way by Chris Rackauckas in his Julia package development tutorial video. However, I found that Travis used to offer a free service for open source project, but apparently this is no longer the case.

Regarding the PyPlot dependency: We can simply comment the `using PyPlot` since the plots aren't created by default anyway (basically, I just used them as sanity check). However, if we want some form of visual check during unit testing, we could use the  [VisualRegressionTests.jl](https://github.com/JuliaPlots/VisualRegressionTests.jl) library in combination with Plots.jl. The downside of course is to have two additional packages as dependencies, which aren't needed for the core package anyway. What do you think?

**Comment by sp94** [comment]
Hi @StefanMathis 

RE Travis vs GitHub actions: I have another repository where I used GitHub actions so I am happy to do the change here

RE PyPlot and visual regression tests: I think it is OK to remove the visual tests. The inputs/outputs of the splines are pretty simple to test directly, and we are not doing anything special with PyPlot that needs to be tested :)

I will sort this in the next few days

**Comment by sp94** [comment]
Added!
